# Generated by Django 4.1.3 on 2022-11-25 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.IntegerField()),
                ('project_name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CallCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_date', models.DateField(blank=True)),
                ('check_up_date', models.DateField(blank=True)),
                ('call_duration', models.IntegerField(blank=True)),
                ('phone_number', models.IntegerField(blank=True)),
                ('record_name', models.CharField(blank=True, max_length=30)),
                ('intro', models.IntegerField(blank=True)),
                ('presentation', models.IntegerField(blank=True)),
                ('purpose', models.IntegerField(blank=True)),
                ('info_to_debtor', models.IntegerField(blank=True)),
                ('payment_options', models.IntegerField(blank=True)),
                ('objections_handling', models.IntegerField(blank=True)),
                ('commitment_closing', models.IntegerField(blank=True)),
                ('farewell', models.IntegerField(blank=True)),
                ('ant_event_result', models.IntegerField(blank=True)),
                ('ant_info', models.IntegerField(blank=True)),
                ('call_model_following', models.IntegerField(blank=True)),
                ('voice_tone', models.IntegerField(blank=True)),
                ('prohibited_phrases', models.IntegerField(blank=True)),
                ('total_score', models.IntegerField(blank=True)),
                ('comments', models.CharField(blank=True, max_length=200)),
                ('call_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.calltype')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.operator')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.project')),
                ('qc_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
