# Generated by Django 4.1.3 on 2022-11-29 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_callcheck_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callcheck',
            name='total_score',
        ),
    ]
