# Generated by Django 4.1.3 on 2022-12-05 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_callcheck_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='callcheck',
            name='op_team',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='app1.team'),
            preserve_default=False,
        ),
    ]
